# Generated by Django 6.0 on 2026-01-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(blank=True, db_index=True, default="default", help_text="Identity source/provider name (e.g., 'telegram', 'max', 'n8n')", max_length=50, verbose_name="Provider")),
                ("external_id", models.CharField(db_index=True, help_text="Stable external identifier within the provider scope", max_length=255, verbose_name="External ID")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional identity data (e.g., workspace, username, raw payload)", verbose_name="Metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update Date")),
                ("user", models.ForeignKey(blank=True, help_text="Optional link to the local Django user model (if applicable)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billable_external_identities", to=settings.AUTH_USER_MODEL, verbose_name="User")),
            ],
            options={
                "verbose_name": "External Identity",
                "verbose_name_plural": "External Identities",
                "db_table": "billable_external_identities",
            },
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["provider"], name="billable_extid_provider_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["external_id"], name="billable_extid_external_id_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["user"], name="billable_extid_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(fields=("provider", "external_id"), name="billable_extid_provider_external_id_uniq"),
        ),
    ]

