# Generated by Django 6.0 on 2026-01-27 00:00

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_products(apps, schema_editor):
    """
    Create 2 default products during migration: TEST_STAR and TEST_PREDICTION.

    Runs before convert_products_to_offers, so offers (get_TEST_STAR, get_TEST_PREDICTION)
    and offer items are created automatically by that step. Product table still has
    price, currency, period_days, quantity at this point (removed later in this migration).
    """
    Product = apps.get_model('billable', 'Product')
    Product.objects.get_or_create(
        product_key='TEST_STAR',
        defaults={
            'name': 'Star (internal currency)',
            'description': '',
            'product_type': 'quantity',
            'price': 1,
            'currency': 'XTR',
            'period_days': None,
            'quantity': 1,
            'is_active': True,
            'is_currency': True,
            'metadata': {},
        },
    )
    Product.objects.get_or_create(
        product_key='TEST_PREDICTION',
        defaults={
            'name': 'Prediction',
            'description': '',
            'product_type': 'quantity',
            'price': 1,
            'currency': 'XTR',
            'period_days': None,
            'quantity': 1,
            'is_active': True,
            'metadata': {},
        },
    )


def convert_products_to_offers(apps, schema_editor):
    Product = apps.get_model('billable', 'Product')
    Offer = apps.get_model('billable', 'Offer')
    OfferItem = apps.get_model('billable', 'OfferItem')
    OrderItem = apps.get_model('billable', 'OrderItem')

    for product in Product.objects.all():
        # Create Offer with 'get_' prefix
        offer_sku = f"get_{product.product_key}" if product.product_key else f"get_prod_{product.id}"
        
        offer = Offer.objects.create(
            sku=offer_sku,
            name=product.name,
            price=getattr(product, 'price', 0),
            currency=getattr(product, 'currency', 'USD'),
            description=product.description,
            is_active=product.is_active,
            metadata=product.metadata
        )
        
        # Determine period unit/value
        period_unit = 'forever'
        period_value = None
        quantity = 1
        
        if product.product_type == 'period':
            period_unit = 'days'
            period_value = getattr(product, 'period_days', 30)
        elif product.product_type == 'quantity':
            quantity = getattr(product, 'quantity', 1)

        # Create OfferItem
        OfferItem.objects.create(
            offer=offer,
            product=product,
            quantity=quantity,
            period_unit=period_unit,
            period_value=period_value
        )

        # Update existing OrderItems that point to this Product
        OrderItem.objects.filter(product_id=product.id).update(offer=offer)


def finalize_test_data(apps, schema_editor):
    """
    Finalize test data: set TEST_PREDICTION offer currency to STAR.
    """
    Offer = apps.get_model('billable', 'Offer')
    Offer.objects.filter(sku='get_TEST_PREDICTION').update(currency='TEST_STAR')


def migrate_inventory_and_history(apps, schema_editor):
    UserProduct = apps.get_model('billable', 'UserProduct')
    QuotaBatch = apps.get_model('billable', 'QuotaBatch')
    ProductUsage = apps.get_model('billable', 'ProductUsage')
    Transaction = apps.get_model('billable', 'Transaction')

    # 1. Migrate UserProducts to QuotaBatches
    up_to_qb_map = {} # Store mapping for history migration
    
    for up in UserProduct.objects.all():
        initial_qty = up.total_quantity if up.total_quantity is not None else 1
        used_qty = getattr(up, "used_quantity", 0) or 0
        remaining_qty = max(0, initial_qty - used_qty)

        qb = QuotaBatch.objects.create(
            user=up.user,
            product=up.product,
            order_item=up.order_item,
            initial_quantity=initial_qty,
            remaining_quantity=remaining_qty,
            valid_from=up.purchased_at,
            expires_at=up.expires_at,
            state='ACTIVE' if up.is_active else 'EXHAUSTED',
            created_at=up.purchased_at
        )
        up_to_qb_map[up.id] = qb
        
        # Create initial CREDIT transaction for migration
        Transaction.objects.create(
            user=up.user,
            quota_batch=qb,
            amount=initial_qty,
            direction='CREDIT',
            action_type='migration',
            created_at=up.purchased_at,
            metadata={'source': 'UserProduct migration'}
        )

    # 2. Migrate ProductUsage to Transactions (content_type left NULL for migrated records)
    for pu in ProductUsage.objects.all():
        qb = up_to_qb_map.get(pu.user_product_id)
        if not qb:
            continue

        meta = dict(pu.metadata) if pu.metadata else {}
        if getattr(pu, "action_type", None):
            meta["action_type_legacy"] = pu.action_type
        if getattr(pu, "action_id", None):
            meta["action_id"] = pu.action_id

        Transaction.objects.create(
            user=pu.user,
            quota_batch=qb,
            amount=1,
            direction="DEBIT",
            action_type="usage",
            object_id=str(pu.id),
            created_at=pu.used_at,
            metadata=meta,
        )


def fill_null_product_prices(apps, schema_editor):
    """
    Set Product.price to 0 where it is NULL so RemoveField(price) does not
    trigger NOT NULL constraint when copying table (e.g. on SQLite).
    """
    Product = apps.get_model("billable", "Product")
    Product.objects.filter(price__isnull=True).update(price=0)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billable", "0001_initial"),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(blank=True, db_index=True, default="default", help_text="Identity source/provider name (e.g., 'telegram', 'max', 'n8n')", max_length=50, verbose_name="Provider")),
                ("external_id", models.CharField(db_index=True, help_text="Stable external identifier within the provider scope", max_length=255, verbose_name="External ID")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional identity data (e.g., workspace, username, raw payload)", verbose_name="Metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update Date")),
                ("user", models.ForeignKey(blank=True, help_text="Optional link to the local Django user model (if applicable)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billable_external_identities", to=settings.AUTH_USER_MODEL, verbose_name="User")),
            ],
            options={
                "verbose_name": "External Identity",
                "verbose_name_plural": "External Identities",
                "db_table": "billable_external_identities",
            },
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["provider"], name="billable_extid_provider_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["external_id"], name="billable_extid_external_id_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["user"], name="billable_extid_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(fields=("provider", "external_id"), name="billable_extid_provider_external_id_uniq"),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Commercial deal identifier. Used for grants and purchases.', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Offer Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('currency', models.CharField(help_text='EUR, USD, XTR, INTERNAL', max_length=10, verbose_name='Currency')),
                ('image', models.ImageField(blank=True, null=True, upload_to='billable/offers/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'billable_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units to grant', verbose_name='Quantity')),
                ('period_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('months', 'Months'), ('years', 'Years'), ('forever', 'Forever')], default='forever', max_length=10, verbose_name='Period Unit')),
                ('period_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Period Value')),
            ],
            options={
                'verbose_name': 'Offer Item',
                'verbose_name_plural': 'Offer Items',
                'db_table': 'billable_offer_items',
            },
        ),
        migrations.CreateModel(
            name='QuotaBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('initial_quantity', models.IntegerField(verbose_name='Initial Quantity')),
                ('remaining_quantity', models.IntegerField(verbose_name='Remaining Quantity')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Quota Batch',
                'verbose_name_plural': 'Quota Batches',
                'db_table': 'billable_quota_batches',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10, verbose_name='Direction')),
                ('action_type', models.CharField(help_text='purchase, referral_bonus, usage, refund', max_length=50, verbose_name='Action Type')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'billable_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='product_key',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_key',
            field=models.CharField(blank=True, help_text="Unique product key (e.g., 'diamonds', 'vip_access')", max_length=50, null=True, unique=True, verbose_name='Product Key'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_currency',
            field=models.BooleanField(default=False, help_text='If True, this product can be used as a currency in the exchange engine.', verbose_name='Is Currency'),
        ),
        migrations.RunPython(create_default_products, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billable.offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billable.offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='billable.product', verbose_name='Product'),
        ),
        migrations.RunPython(convert_products_to_offers, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(finalize_test_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='orderitem',
            name='period_days',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='quotabatch',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billable.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='quotabatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_batches', to='billable.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='quotabatch',
            name='source_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billable.offer', verbose_name='Source Offer'),
        ),
        migrations.AddField(
            model_name='quotabatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_batches', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quota_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billable.quotabatch', verbose_name='Quota Batch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RunPython(migrate_inventory_and_history, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Product Description'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='period_days',
        ),
        migrations.RunPython(fill_null_product_prices, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddIndex(
            model_name='quotabatch',
            index=models.Index(fields=['user', 'product', 'state'], name='billable_qb_user_prod_state'),
        ),
        migrations.AddIndex(
            model_name='quotabatch',
            index=models.Index(fields=['expires_at'], name='billable_qb_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='billable_tx_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['action_type'], name='billable_tx_action_type_idx'),
        ),
        migrations.DeleteModel(
            name='ProductUsage',
        ),
        migrations.DeleteModel(
            name='UserProduct',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(settings.AUTH_USER_MODEL.lower(),),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
